site_name: Récupération d'eaux pluviales

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.tab
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - content.code.annotate
    - content.code.copy
    - toc.follow


nav:

  - home.md
  - Projet:
    - Projet/besoins.ipynb
    - Projet/pluie.ipynb

 # - Source:
 #   - references.bib

#  - Code Reference: references.bib
 # - changelog.md
 # - roadmap.md

extra_css:
  - assets/stylesheets/extra.css
  - assets/termynal/termynal.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - assets/termynal/termynal.js

watch:
  - roadmap.md
  - changelog.md

extra:
  version:
    provider: mike

plugins:
  - search
  - bibtex:
      bib_file: "docs/references.bib"
      bib_command: "docs/bibliography"
  - gen-files:
      scripts:
        - docs/scripts/reference.py
        - docs/scripts/development.py
  - literate-nav:
      nav_file: SUMMARY.md
  - autorefs
  - mkdocs-jupyter:
      show_input: False
      no_input: True
      execute: false
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            heading_level: 2
            members_order: source
            show_root_toc_entry: false
  - glightbox:
      touchNavigation: true
      loop: false
      effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - mike:
      version_selector: false
      css_dir: assets/css
      javascript_dir: assets/js

      

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
  #        format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - toc: 
      permalink: true
  - md_in_html
  - attr_list
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:

#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg